### ISSUE TITLE
Parent doesn't work, all microservices got Error: ENOENT

### ISSUE THREAD

**Issue by ramdhan-h** [leocristofani/microfrontends-in-practice#1]
1. Error: ENOENT: no such file or directory, scandir '.../artists/server/public/embed'
2. Error: ENOENT: no such file or directory, scandir '.../playlist/server/public/embed'
3. Error: ENOENT: no such file or directory, scandir '.../songs/server/public/embed'

**Comment by tanzilgr2288** [comment]
The problem is, the run_build.sh should not running the webpack.embed.js

Try to install webpack on your local

for mac user

> brew install webpack

and try to rebuild again

AbraKadabra.. Magic happend..

**Comment by ramdhan-h** [comment]
[SOLVED] Need to install webpack globally.
